name: "default-ultrasight"
author: "Your Name"
description: "Description of default-ultrasight."
category: "FPV"
sensor: ""  # Set sensor file if needed
status: "Community"
tags: ["default-ultrasight"]
files:
  wfb.yaml:
    wireless.channel: "161"
    wireless.txpower: "1"
    broadcast.stbc: "0"
    broadcast.ldpc: "0"
    broadcast.mcs_index: "1"
    broadcast.tun_index: "1"
    broadcast.fec_k: "8"
    broadcast.fec_n: "12"  
    telemetry.serial: ttyS2
    telemetry.router: msposd
  
  majestic.yaml:
    fpv.enabled: "true"
    fpv.noiseLevel: "0"
    system.logLevel: "debug"
    video0.codec: "h265"
    video0.fps: "60"
    video0.bitrate: "4096"
    video0.size: "1920x1080"
    
