name: "emax-preset"
author: "carabidule"
description: "msp menu, tx power mw, add alink in msp menu"
category: "FPV"
sensor: ""  # Set sensor file if needed
status: "Experimental"
tags: ["emax", "msp"]
files:
  wfb.conf:
    txpower: "1"
    channel: "161"
    driver_txpower_override: "30"
    stbc: "1"
    ldpc: "1"
    mcs_index: "1"
    fec_k: "8"
    fec_n: "12"
  telemetry.conf:
    serial: /dev/ttyS0
    # 2 for msposd
    router: 2 

  majestic.yaml:
    fpv.enabled: "true"
    fpv.noiseLevel: "0"
    system.logLevel: "debug"
    video0.codec: "h265"
    video0.fps: "120"
    video0.bitrate: "4096"
    video0.size: "1280x720"
  
  external_files:
    vtxmenu.ini
    txprofiles.conf
    alink_drone
    alink.conf

     
  
    
